---
apiVersion: v1
kind: Secret
metadata:
  name: mgthies-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-lab/mgthies-gateway-gitops
